server:
  port: 8090

spring:
  profiles:
    active: dev
    include: secret
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./test_db;MODE=MYSQL;
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 100
        use_sql_comments: true
    open-in-view: false
  threads:
    virtual:
      enabled: true
  kafka:
    bootstrap-servers: localhost:19092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin



logging:
  level:
    com.example.rabbitmq_stomp: debug
    org.hibernate.sql : debug
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
