server:
  port: 8090

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./test_db;MODE=MYSQL;
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 100
        use_sql_comments: true
    open-in-view: false
  threads:
    virtual:
      enabled: true
  rabbitmq:
    host: ${custom.prod.rabbitmq.host}
    port: ${custom.prod.rabbitmq.port}
    stompPort: ${custom.prod.rabbitmq.stompPort}
    username: ${custom.prod.rabbitmq.username}
    password: ${custom.prod.rabbitmq.password}

jwt:
  secretKey: ${custom.jwt.secret}

custom:
  dev:
    cookieDomain:
    frontUrl:
    backUrl:
  prod:
    cookieDomain:
    frontUrl:
    backUrl:
  service:
    domain:
    frontUrl:
    backUrl:
    name:

logging:
  level:
    com.example.rabbitmq_stomp: debug
    org.hibernate.sql : debug
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
